### PR TITLE
Added example using regionmask for regional skill

### PR DESCRIPTION
**Pull request by hdrake**
Uses Riley's new pull request for adding skipna=True as an optional
argument to xskillscore! Thanks to Arianna for the example code for
applying the regional masks!

### CODE REVIEW

**Comment by bradyrx** [comment]
A note on the `xskillscore` installation instructions. Once it is merged into master and uploaded to pip (which Ray usually does pretty quickly after a new feature like this), we can just enforce the updated `xskillscore` version in the yaml file. E.g., `xskillscore >= 0.9` or whatever the new version will be.

**Review by bradyrx — APPROVED** [review]
Looks good to me! Just noticed all the files changed was just deleting the xskillscore subdirectory you were using for installation. My branch should stay stable, but will alert you if Ray requests a lot of changes to it and it's temporarily broken.

**Comment by hdrake** [comment]
Combined Southern American regions (rectangular land + ocean regions) with land mask to apply a mask for just the Southern American continent.

Also included a notebook for looking at skill for the climatological seasonal cycle (relative to long-term mean).

**Comment by hdrake** [comment]
Addresses https://github.com/hdrake/cmip6hack-multigen/issues/17.

**Pull request merged**
